renamePakage
IdaliaGeeks/holiday_jp-go pull request #11
Opened 2024-08-06 23:15 UTC by ababaSigrun

I've created the changes for now. The tests passed successfully, so I've submitted a pull request.

2024-08-08 12:46 UTC, Kiyo510 requested changes
@ababaSigrun 
Thank you for your prompt response!
Please check my comment...!

Also, I corrected the issue and PR title because this was a mistake in the module name, not the package name 🙏

2024-08-08 12:46 UTC, Kiyo510 commented on datasheet.go
> -package holiday
[imo]
What is the reason for changing the package name here? 👀

I don't think it's necessary to break the naming conventions to make the package name consistent with the repository name, since Go recommends using a single word for package names except for "test".
In the future, I would like to separate directories and hierarchies properly, so I think it's fine to keep the current names.

https://go.dev/blog/package-names
> Good package names are short and clear. They are lower case, with no under_scores or mixedCaps. They are often simple nouns, such as:

2024-08-08 12:46 UTC, Kiyo510 commented on gen/go.mod
> -module github.com/holiday-jp/holiday_jp-go/gen
[must]
Please also rename `go.mod` in the repository root!

2024-08-08 12:50 UTC, Kiyo510 commented
@ababaSigrun 
Also, when designating reviewers, it is OK to have only the `Beryl` team set up.

2024-08-08 13:17 UTC, ababaSigrun commented on datasheet.go
> -package holiday
I'll read through it

2024-08-21 17:43 UTC, ababaSigrun commented on datasheet.go
> -package holiday
It took some time, but I read it.

2024-08-21 18:05 UTC, ababaSigrun commented on datasheet.go
> -package holiday
iI'd like to confirm what I will do after reading the documentation.

Restore the pakege to its original state.

After that, I need to update the module in gen/go.mod.

I think the module github.com/IdaliaGeeks/holiday_jp-go/gen is correct, but what do you think?

2024-08-29 13:40 UTC, Kiyo510 approved these changes

2024-08-29 13:41 UTC, merged